import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import NavBarSection from "./components/NavBarSection";
import FontAwesomeConfig from "./fontawesome";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Siddhant Pandey",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <FontAwesomeConfig />
      </head>
      <body>
        <NavBarSection />
        {children}
      </body>
    </html>
  );
}
